<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '(&copy; MuliSoft ) date("Y")' => '',
    'About' => '',
    'Activo' => '',
    'Are you sure you want to delete this item?' => '',
    'Assign Productos' => '',
    'Cantidad' => '',
    'Categoria' => '',
    'Categorias' => '',
    'Comercio' => '',
    'Comercio Productos' => '',
    'Comercio Productos Relacionados' => '',
    'Comercios' => '',
    'Congratulations!' => '',
    'Contact' => '',
    'Create' => '',
    'Create Categoria' => '',
    'Create Comercio' => '',
    'Create Comercio Producto' => '',
    'Create Comercio Productos Relacionados' => '',
    'Create Orden Comercio' => '',
    'Create Pedido' => '',
    'Create Producto' => '',
    'Create Ruta' => '',
    'Create Ruta Diaria' => '',
    'Create Ruta Diaria Comercio' => '',
    'Create Stock' => '',
    'Delete' => '',
    'Descripcion' => '',
    'Dia' => '',
    'Direccion' => '',
    'Es Activo' => '',
    'Fecha' => '',
    'Get started with Yii' => '',
    'Home' => '',
    'ID' => '',
    'Id Comercio' => '',
    'Id Producto' => '',
    'Id Ruta' => '',
    'Id Ruta Diaria' => '',
    'Id Ruta Diaria Comercio' => '',
    'Imagen' => '',
    'Latitud' => '',
    'Login' => '',
    'Logout (' => '',
    'Longitud' => '',
    'Muli Relevators' => '',
    'MuliSoft' => '',
    'Nombre' => '',
    'Orden' => '',
    'Orden Comercios' => '',
    'Pedidos' => '',
    'Please contact us if you think this is a server error. Thank you.' => '',
    'Precio' => '',
    'Prioridad' => '',
    'Producto' => '',
    'Productos' => '',
    'Reset' => '',
    'Ruta Diaria Comercios' => '',
    'Ruta Diarias' => '',
    'Rutas' => '',
    'Search' => '',
    'Signup' => '',
    'Stocks' => '',
    'The above error occurred while the Web server was processing your request.' => '',
    'Update' => '',
    'Update {modelClass}: ' => '',
    'Vendidos' => '',
    'You have successfully created your Yii-powered application.' => '',
];
