<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Are you sure???' => '',
    'Error on initialization!!' => '',
    'Error when loading Store products!!' => '',
    'Error while trying to save the order!!' => '',
    'Error while trying to save the stock!!' => '',
    'Failed to save orders data...' => '',
    'Failed to save route with id: ' => '',
    'Home' => '',
    'Log In' => '',
    'Logout' => '',
    'Muli Relevators' => '',
    'Muli Relevators Mobile' => '',
    'Muli Relevators. All Right Reserved.' => '',
    'Not able to load stores!!!' => '',
    'Orders' => '',
    'Password' => '',
    'Routes' => '',
    'Select store...' => '',
    'Stock' => '',
    'Submit' => '',
    'Thank you for use our app!!' => '',
    'The stock has been saved succesfully!!' => '',
    'To use our app, select an option from the nav menu.' => '',
    'Username' => '',
    'Welcome back!' => '',
    'You completed all your tasks for today!!' => '',
    'You have undone your selection!!!' => '',
    'Your order has been saved...thanks!!' => '',
];
