<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Activo' => 'Activo',
    'Are you sure you want to delete this item?' => 'Está seguro que desea eliminar este item?',
    'Assign Productos' => 'Asignar Prodctos',
    'Cantidad' => 'Cantidad',
    'Categoria' => 'Categoria',
    'Categorias' => 'Categorias',
    'Comercio' => 'Comercio',
    'Comercio Productos' => 'Productos del Comercio',
    'Comercio Productos Relacionados' => 'Productos Relacionados del Comercio',
    'Comercios' => 'Comercios',
    'Create' => 'Crear',
    'Create Categoria' => 'Crear Categoría',
    'Create Comercio' => 'Crear Comercio',
    'Create Comercio Producto' => 'Crear Producto del Comercio',
    'Create Comercio Productos Relacionados' => 'Crear Productos Relacionados al Comercio',
    'Create Orden Comercio' => 'Crear Orden Comercio',
    'Create Pedido' => 'Crear Pedido',
    'Create Producto' => 'Crear Producto',
    'Create Ruta' => 'Crear ruta',
    'Create Ruta Diaria' => 'Crear ruta diaria',
    'Create Ruta Diaria Comercio' => 'Crear ruta diaria comercio',
    'Create Stock' => 'Crear Stock',
    'Delete' => 'Eliminar',
    'Descripcion' => 'Descripción',
    'Dia' => 'Día',
    'Direccion' => 'Dirección',
    'Es Activo' => 'Es Activo',
    'Fecha' => 'Fecha',
    'ID' => 'ID',
    'Id Comercio' => 'Id Comercio',
    'Id Producto' => 'Id Producto',
    'Id Ruta' => 'Id Ruta',
    'Id Ruta Diaria' => 'Id Ruta Diaria',
    'Id Ruta Diaria Comercio' => 'Id Ruta Diaria Comercio',
    'Imagen' => 'Imagen',
    'Latitud' => 'Latitud',
    'Longitud' => 'Longitud',
    'Nombre' => 'Nombre',
    'Orden' => 'Orden',
    'Orden Comercios' => 'Orden Comercios',
    'Pedidos' => 'Pedidos',
    'Precio' => 'Precio',
    'Prioridad' => 'Prioridad',
    'Producto' => 'Producto',
    'Productos' => 'Productos',
    'Reset' => 'Reset',
    'Ruta Diaria Comercios' => 'Ruta Diaria Comercios',
    'Ruta Diarias' => 'Ruta Diarias',
    'Rutas' => 'Rutas',
    'Search' => 'Buscar',
    'Stocks' => 'Stocks',
    'Update' => 'Actualizar',
    'Update {modelClass}: ' => 'Actualizar {modelClass}: ',
    'Vendidos' => 'Vendidos',
];
