<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Country Code' => 'Código de País',
    'Create' => 'Crear',
    'Create Cities' => 'Crear Ciudades',
    'Create Country' => 'Crear País',
    'Created At' => 'Creado en',
    'Delete' => 'Eliminar',
    'Name' => 'Nombre',
    'Population' => 'Población',
    'Reset' => 'Restablecer',
    'Search' => 'Buscar',
    'Update' => 'Actualizar',
    'Update {modelClass}: ' => 'Actualizar {modelClass}: ',
    'Updated At' => 'Actualizado el',
    'Are you sure you want to delete this item?' => '¿Está seguro de eliminar este elemento?',
    'Cities' => 'Ciudades',
    'City Code' => 'Codigo de Ciudad',
    'City Name' => 'Nombre de Ciudad',
    'Code' => 'Codigo',
    'Countries' => 'Paises',
];
