<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Are you sure???' => 'Está seguro??',
    'Error while trying to save the order!!' => 'Error al intentar salvar la Orden',
    'Error while trying to save the stock!!' => 'Error al intentar salvar el Comercio',
    'Failed to save orders data...' => 'Fallo al guardar los datos de la Orden',
    'Failed to save route with id: ' => 'Fallo al guardar la Ruta con Id: ',
    'Logout' => 'Desloguear',
    'Muli Relevators' => 'Muli Relevadores',
    'Muli Relevators Mobile' => 'Muli Relevadores Mobile',
    'Not able to load stores!!!' => 'No fue posible cargar Comercios!!!',
    'Thank you for use our app!!' => 'Gracias por usar nuestra aplicación!!',
    'The stock has been saved succesfully!!' => 'El Stock fue guardado exitosamente!!',
    'To use our app, select an option from the nav menu.' => 'Para usar nuestra aplicación seleccione una opción del menú',
    'Welcome back!' => 'Bienvenido nuevamente!',
    'You completed all your tasks for today!!' => 'Ha completado todas las tareas de hoy!!',
    'You have undone your selection!!!' => 'Ha deshecho su selección!!',
    'Your order has been saved...thanks!!' => 'Su Orden fue guardada... Gracias!!',
    'Error on initialization!!' => 'Error al inicializar!!',
    'Error when loading Store products!!' => 'Error al cargar los productos del comercio',
    'Home' => 'Inicio',
    'Log In' => 'Ingresar',
    'Muli Relevators' => 'Muli Relevadores',
    'Muli Relevators. All Right Reserved.' => 'Muli Relevadores. © Derechos reservados.',
    'Orders' => 'Pedidos',
    'Password' => 'Contraseña',
    'Routes' => 'Rutas',
    'Select store...' => 'Seleccione Comercio...',
    'Stock' => 'Stock',
    'Submit' => 'Enviar',
    'Username' => 'Nombre usuario',
];
